name: "On-push checks"

on: ["push"]

jobs:
  run-tests:
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Install dependencies"
        env:
          XDEBUG_MODE: "coverage"
          COMPOSER_AUTH: '{"github-oauth":{"github.com":"${{ secrets.COMPOSER_GITHUB_TOKEN }}"}}'
        run: 'composer update'

      - name: "Run PHPUnit tests"
        run: "./bin/phpunit"
