name: "On-push checks"

on: ["push"]

jobs:
  run-tests:
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Install composer"
        uses: "php-actions/composer@v6"

      - name: "Install dependencies"
        run: 'COMPOSER_AUTH={"github-oauth":{"github.com":"${{ secrets.COMPOSER_GITHUB_TOKEN }}"}} composer update'

      - name: "Run PHPUnit tests"
        run: "composer test"
